version = 1
SPDX-PackageName = "xml-tools"
SPDX-PackageSupplier = "Shachar Soel <shachar.soel@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/SAP/xml-tools"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019-2024 SAP SE or an SAP affiliate company and XML Tools contributors"
SPDX-License-Identifier = "Apache-2.0"
